package middleware

import (
	"context"
	"fmt"
	"strings"

	"github.com/grafaelw/golangchain/llm"
	"github.com/grafaelw/golangchain/schema"
)

// ---------------------------------------------------------------------------
// SummarizationMiddleware
// ---------------------------------------------------------------------------

// SummarizationMiddleware compresses conversation history when it exceeds a
// token threshold, keeping the most recent messages verbatim and replacing
// older messages with a summary generated by the model.
type SummarizationMiddleware struct {
	NoOpMiddleware
	Model      llm.LLM
	MaxTokens  int
	KeepRecent int
}

// SummarizationOption configures a SummarizationMiddleware.
type SummarizationOption func(*SummarizationMiddleware)

// NewSummarizationMiddleware constructs a SummarizationMiddleware.
func NewSummarizationMiddleware(model llm.LLM, opts ...SummarizationOption) *SummarizationMiddleware {
	s := &SummarizationMiddleware{
		Model:      model,
		MaxTokens:  4000,
		KeepRecent: 4,
	}
	for _, o := range opts {
		o(s)
	}
	return s
}

func (s *SummarizationMiddleware) Name() string { return "Summarization" }

// WithSummarizationMaxTokens sets the token threshold for triggering summarization.
func WithSummarizationMaxTokens(n int) SummarizationOption {
	return func(s *SummarizationMiddleware) { s.MaxTokens = n }
}

// WithSummarizationKeepRecent sets the number of recent messages to keep verbatim.
func WithSummarizationKeepRecent(n int) SummarizationOption {
	return func(s *SummarizationMiddleware) { s.KeepRecent = n }
}

func (s *SummarizationMiddleware) BeforeModel(ctx context.Context, messages []schema.Message, steps []schema.AgentStep) ([]schema.Message, error) {
	estimated := estimateTokens(messages)
	if estimated <= s.MaxTokens || len(messages) <= s.KeepRecent {
		return messages, nil
	}

	toSummarize := messages[:len(messages)-s.KeepRecent]
	summary, err := s.summarize(ctx, toSummarize)
	if err != nil {
		return messages, nil
	}

	var result []schema.Message
	result = append(result, schema.NewSystemMessage("Previous conversation summary:\n"+summary))
	result = append(result, messages[len(messages)-s.KeepRecent:]...)
	return result, nil
}

func (s *SummarizationMiddleware) summarize(ctx context.Context, messages []schema.Message) (string, error) {
	var sb strings.Builder
	for _, m := range messages {
		fmt.Fprintf(&sb, "%s: %s\n", m.Role, m.Content)
	}

	prompt := []schema.Message{
		schema.NewSystemMessage("Summarize the following conversation concisely. Preserve key facts, decisions, and action items."),
		schema.NewHumanMessage(sb.String()),
	}

	gen, err := s.Model.Generate(ctx, prompt)
	if err != nil {
		return "", err
	}
	return gen.Text, nil
}

func estimateTokens(messages []schema.Message) int {
	total := 0
	for _, m := range messages {
		total += len(m.Content) / 4
		for _, tc := range m.ToolCalls {
			total += len(tc.Name) + len(tc.Arguments)/4
		}
	}
	return total
}
